#include "TileManager.h"
#include <set>
#include <algorithm>

// ============================================================================
// Symmetry-aware rule deduplication
// ============================================================================
// The WFC engine auto-expands each horizontal rule into up to 4 equivalent
// propagator entries (base, 180deg, mirror, mirror180). Two editor connections
// that map to the same set of propagator entries are redundant — we only need
// one in the XML.
//
// canonRot:     reduce rotation to canonical range by symmetry
// applyRot180:  what rotation index results from rotating 180deg
// applyMirror:  what rotation index results from mirroring (the b function)
// ============================================================================

namespace {

// Reduce rotation to the canonical representative for this symmetry.
// X: cardinality 1 → all rotations are 0
// I, \: cardinality 2 → rot 0≡2, rot 1≡3
// L, T, +: cardinality 4 → all distinct
int canonRot(int rot, const std::string& sym) {
    if (sym == "X") return 0;
    if (sym == "I" || sym == "\\") return rot % 2;
    return rot;
}

// Result of rotating 180deg (a(a(rot))). For I/\, 180=identity.
int applyRot180(int rot, const std::string& sym) {
    if (sym == "X") return 0;
    if (sym == "I" || sym == "\\") return rot;
    return (rot + 2) % 4;
}

// The mirror function b(rot) matching ofxWFC3D's symmetry definitions.
int applyMirror(int rot, const std::string& sym) {
    if (sym == "X") return 0;
    if (sym == "I" || sym == "+") return rot;          // b(i)=i
    if (sym == "\\") return 1 - rot;                   // b(i)=1-i (canonical 0,1)
    if (sym == "L") return (rot % 2 == 0) ? rot + 1 : rot - 1;  // 0↔1, 2↔3
    if (sym == "T") return (rot % 2 == 0) ? rot : 4 - rot;      // keep 0,2; swap 1↔3
    return rot;
}

struct HRuleKey {
    std::string leftName, rightName;
    int leftRot, rightRot;

    bool operator<(const HRuleKey& o) const {
        if (leftName != o.leftName) return leftName < o.leftName;
        if (leftRot != o.leftRot) return leftRot < o.leftRot;
        if (rightName != o.rightName) return rightName < o.rightName;
        return rightRot < o.rightRot;
    }
    bool operator==(const HRuleKey& o) const {
        return leftName == o.leftName && leftRot == o.leftRot &&
               rightName == o.rightName && rightRot == o.rightRot;
    }
};

// Given a horizontal rule and both tiles' symmetries, return the canonical form
// by generating all equivalent forms the WFC engine would produce and picking
// the lexicographically smallest.
HRuleKey canonicalizeHRule(const std::string& lName, int lRot, const std::string& lSym,
                           const std::string& rName, int rRot, const std::string& rSym) {
    lRot = canonRot(lRot, lSym);
    rRot = canonRot(rRot, rSym);

    std::vector<HRuleKey> forms;

    // Form 1: base
    forms.push_back({lName, rName, lRot, rRot});

    // Form 2: 180deg swap (always generated by engine)
    forms.push_back({rName, lName,
                     canonRot(applyRot180(rRot, rSym), rSym),
                     canonRot(applyRot180(lRot, lSym), lSym)});

    // Mirror forms only if neither tile has "+" symmetry
    if (lSym != "+" && rSym != "+") {
        // Form 3: mirror
        forms.push_back({rName, lName,
                         canonRot(applyMirror(rRot, rSym), rSym),
                         canonRot(applyMirror(lRot, lSym), lSym)});

        // Form 4: mirror of 180deg
        forms.push_back({lName, rName,
                         canonRot(applyMirror(applyRot180(lRot, lSym), lSym), lSym),
                         canonRot(applyMirror(applyRot180(rRot, rSym), rSym), rSym)});
    }

    return *std::min_element(forms.begin(), forms.end());
}

} // anonymous namespace

void TileManager::loadModelsFromDirectory(const std::string& directory) {
    tiles.clear();
    uniformScale = 0.0f;

    ofDirectory dir(directory);
    auto exts = loaderFactory.getAllSupportedExtensions();
    for (auto& ext : exts) {
        dir.allowExt(ext);
    }
    dir.listDir();
    dir.sort();

    for (auto& file : dir) {
        Tile tile;
        tile.name = ofFilePath::removeExt(file.getFileName());
        // Skip any file named "empty" — we add that ourselves at the end
        if (tile.name == "empty") continue;
        if (loaderFactory.load(file.getAbsolutePath(), tile.mesh)) {
            ofLogNotice("TileManager") << "Loaded: " << tile.name;
            tiles.push_back(std::move(tile));
        } else {
            ofLogWarning("TileManager") << "Failed to load: " << file.getFileName();
        }
    }

    // Compute global max dimension across all loaded meshes
    for (auto& tile : tiles) {
        auto& verts = tile.mesh.getVertices();
        if (verts.empty()) continue;
        glm::vec3 minB(FLT_MAX), maxB(-FLT_MAX);
        for (auto& v : verts) {
            minB = glm::min(minB, v);
            maxB = glm::max(maxB, v);
        }
        glm::vec3 size = maxB - minB;
        float maxDim = std::max({size.x, size.y, size.z});
        uniformScale = std::max(uniformScale, maxDim);
    }
    if (uniformScale <= 0.0f) uniformScale = 1.0f;

    // Always add empty tile last (no mesh, symmetry X)
    Tile emptyTile;
    emptyTile.name = "empty";
    emptyTile.symmetry = "X";
    tiles.push_back(std::move(emptyTile));

    ofLogNotice("TileManager") << "Loaded " << tiles.size() << " tiles (including empty)";
    ofLogNotice("TileManager") << "Uniform scale base: " << uniformScale;
}

void TileManager::layoutTiles(float spacing) {
    int cols = std::max(1, (int)std::ceil(std::sqrt((float)tiles.size())));
    for (size_t i = 0; i < tiles.size(); i++) {
        int col = i % cols;
        int row = i / cols;
        tiles[i].position = glm::vec3(col * spacing, 0, row * spacing);
    }
}

bool TileManager::addConnection(int tileA, CubeFace faceA, int tileB, CubeFace faceB) {
    Connection c{tileA, faceA, tileB, faceB};
    for (auto& existing : connections) {
        if (existing == c) return false;
    }
    connections.push_back(c);
    return true;
}

bool TileManager::removeConnection(int tileA, CubeFace faceA, int tileB, CubeFace faceB) {
    Connection c{tileA, faceA, tileB, faceB};
    for (auto it = connections.begin(); it != connections.end(); ++it) {
        if (*it == c) {
            connections.erase(it);
            return true;
        }
    }
    return false;
}

bool TileManager::toggleConnection(int tileA, CubeFace faceA, int tileB, CubeFace faceB) {
    if (removeConnection(tileA, faceA, tileB, faceB)) {
        return false;  // was removed
    }
    addConnection(tileA, faceA, tileB, faceB);
    return true;  // was added
}

void TileManager::setSymmetry(int tileIndex, const std::string& sym) {
    if (tileIndex >= 0 && tileIndex < (int)tiles.size()) {
        tiles[tileIndex].symmetry = sym;
    }
}

std::vector<const Connection*> TileManager::getConnectionsForFace(int tileIndex, CubeFace face) const {
    std::vector<const Connection*> result;
    for (auto& c : connections) {
        if ((c.tileA == tileIndex && c.faceA == face) ||
            (c.tileB == tileIndex && c.faceB == face)) {
            result.push_back(&c);
        }
    }
    return result;
}

// Rotation mapping for the "left" tile in a horizontal rule:
// At rotation 0, the tile's right face (+X) is the connecting surface to the right neighbor
// CCW: RIGHT=0, FRONT=1, LEFT=2, BACK=3
int TileManager::faceToRotationLeft(CubeFace face) {
    switch (face) {
        case FACE_RIGHT: return 0;
        case FACE_FRONT: return 1;
        case FACE_LEFT:  return 2;
        case FACE_BACK:  return 3;
        default: return 0;
    }
}

// Rotation mapping for the "right" tile in a horizontal rule:
// At rotation 0, the tile's left face (-X) is the connecting surface to the left neighbor
// CCW: LEFT=0, BACK=1, RIGHT=2, FRONT=3
int TileManager::faceToRotationRight(CubeFace face) {
    switch (face) {
        case FACE_LEFT:  return 0;
        case FACE_BACK:  return 1;
        case FACE_RIGHT: return 2;
        case FACE_FRONT: return 3;
        default: return 0;
    }
}

std::string TileManager::faceName(CubeFace f) {
    switch (f) {
        case FACE_LEFT:   return "Left";
        case FACE_RIGHT:  return "Right";
        case FACE_BOTTOM: return "Bottom";
        case FACE_TOP:    return "Top";
        case FACE_BACK:   return "Back";
        case FACE_FRONT:  return "Front";
    }
    return "?";
}

int TileManager::rotationLabelForFace(CubeFace f) {
    // Show rotation index on side faces (using "right" tile mapping)
    return faceToRotationRight(f);
}

CubeFace TileManager::rotationToFaceLeft(int rot) {
    switch (rot) {
        case 0: return FACE_RIGHT;
        case 1: return FACE_FRONT;
        case 2: return FACE_LEFT;
        case 3: return FACE_BACK;
    }
    return FACE_RIGHT;
}

CubeFace TileManager::rotationToFaceRight(int rot) {
    switch (rot) {
        case 0: return FACE_LEFT;
        case 1: return FACE_BACK;
        case 2: return FACE_RIGHT;
        case 3: return FACE_FRONT;
    }
    return FACE_LEFT;
}

int TileManager::findTileByName(const std::string& name) const {
    for (size_t i = 0; i < tiles.size(); i++) {
        if (tiles[i].name == name) return (int)i;
    }
    return -1;
}

void TileManager::loadXml(const std::string& path) {
    connections.clear();

    ofFile file(path);
    if (!file.exists()) {
        ofLogNotice("TileManager") << "No existing XML at " << path;
        return;
    }

    ofXml xml;
    if (!xml.load(path)) {
        ofLogWarning("TileManager") << "Failed to parse XML: " << path;
        return;
    }

    auto set = xml.getChild("set");
    if (!set) return;

    // Read tile symmetries
    auto xmlTiles = set.getChild("tiles");
    if (xmlTiles) {
        for (auto& xmlTile : xmlTiles.getChildren("tile")) {
            std::string name = xmlTile.getAttribute("name").getValue();
            std::string sym = xmlTile.getAttribute("symmetry").getValue();
            int idx = findTileByName(name);
            if (idx >= 0 && !sym.empty()) {
                tiles[idx].symmetry = sym;
            }
        }
    }

    // Read neighbors
    auto xmlNeighbors = set.getChild("neighbors");
    if (!xmlNeighbors) return;

    for (auto& child : xmlNeighbors.getChildren()) {
        std::string tag = child.getName();

        if (tag == "horizontal") {
            std::string leftStr = child.getAttribute("left").getValue();
            std::string rightStr = child.getAttribute("right").getValue();

            // Parse "tileName" or "tileName rotation"
            auto parseTileRot = [](const std::string& s, std::string& name, int& rot) {
                rot = 0;
                auto spacePos = s.find(' ');
                if (spacePos == std::string::npos) {
                    name = s;
                } else {
                    name = s.substr(0, spacePos);
                    rot = ofToInt(s.substr(spacePos + 1));
                }
            };

            std::string leftName, rightName;
            int leftRot, rightRot;
            parseTileRot(leftStr, leftName, leftRot);
            parseTileRot(rightStr, rightName, rightRot);

            int tileA = findTileByName(leftName);
            int tileB = findTileByName(rightName);
            if (tileA >= 0 && tileB >= 0) {
                CubeFace faceA = rotationToFaceLeft(leftRot);
                CubeFace faceB = rotationToFaceRight(rightRot);
                addConnection(tileA, faceA, tileB, faceB);
            }
        } else if (tag == "vertical") {
            std::string bottomStr = child.getAttribute("bottom").getValue();
            std::string topStr = child.getAttribute("top").getValue();

            // Vertical doesn't use rotations in the XML
            std::string bottomName = bottomStr, topName = topStr;
            auto sp1 = bottomStr.find(' ');
            if (sp1 != std::string::npos) bottomName = bottomStr.substr(0, sp1);
            auto sp2 = topStr.find(' ');
            if (sp2 != std::string::npos) topName = topStr.substr(0, sp2);

            int tileBottom = findTileByName(bottomName);
            int tileTop = findTileByName(topName);
            if (tileBottom >= 0 && tileTop >= 0) {
                // bottom's TOP face connects to top's BOTTOM face
                addConnection(tileBottom, FACE_TOP, tileTop, FACE_BOTTOM);
            }
        }
    }

    ofLogNotice("TileManager") << "Loaded " << connections.size() << " connections from " << path;
}

std::vector<std::string> TileManager::getTilesWithConnections() const {
    std::set<int> indices;
    for (auto& c : connections) {
        indices.insert(c.tileA);
        indices.insert(c.tileB);
    }
    std::vector<std::string> names;
    for (int idx : indices) {
        if (idx >= 0 && idx < (int)tiles.size()) {
            names.push_back(tiles[idx].name);
        }
    }
    return names;
}

void TileManager::saveXml(const std::string& path) {
    ofXml xml;
    auto set = xml.appendChild("set");

    // Tiles
    auto xmlTiles = set.appendChild("tiles");
    for (auto& tile : tiles) {
        auto xmlTile = xmlTiles.appendChild("tile");
        xmlTile.setAttribute("name", tile.name);
        xmlTile.setAttribute("symmetry", tile.symmetry);
    }

    // Neighbors — deduplicated, horizontal grouped by left tile, then vertical by bottom tile
    auto xmlNeighbors = set.appendChild("neighbors");

    struct HRule { std::string left, right; int leftIdx; };
    struct VRule { std::string bottom, top; int bottomIdx; };
    std::vector<HRule> hRules;
    std::vector<VRule> vRules;

    std::set<HRuleKey> seenH;
    std::set<std::pair<std::string, std::string>> seenV;

    for (auto& c : connections) {
        bool verticalConnection =
            (c.faceA == FACE_TOP && c.faceB == FACE_BOTTOM) ||
            (c.faceA == FACE_BOTTOM && c.faceB == FACE_TOP);

        if (verticalConnection) {
            int bottomTile, topTile;
            if (c.faceA == FACE_TOP) {
                bottomTile = c.tileA;
                topTile = c.tileB;
            } else {
                bottomTile = c.tileB;
                topTile = c.tileA;
            }
            // Vertical: dedup by exact (bottom, top) pair
            auto key = std::make_pair(tiles[bottomTile].name, tiles[topTile].name);
            if (seenV.insert(key).second) {
                vRules.push_back({tiles[bottomTile].name, tiles[topTile].name, bottomTile});
            }
        } else if (isSideFace(c.faceA) && isSideFace(c.faceB)) {
            int rotA = faceToRotationLeft(c.faceA);
            int rotB = faceToRotationRight(c.faceB);

            // Symmetry-aware dedup: check if this rule is equivalent to one already seen
            auto canonical = canonicalizeHRule(
                tiles[c.tileA].name, rotA, tiles[c.tileA].symmetry,
                tiles[c.tileB].name, rotB, tiles[c.tileB].symmetry);

            if (seenH.insert(canonical).second) {
                // Use the canonical form for clean output
                std::string leftVal = canonical.leftName;
                if (canonical.leftRot != 0) leftVal += " " + ofToString(canonical.leftRot);

                std::string rightVal = canonical.rightName;
                if (canonical.rightRot != 0) rightVal += " " + ofToString(canonical.rightRot);

                // Find left tile index for sorting
                int leftIdx = findTileByName(canonical.leftName);
                hRules.push_back({leftVal, rightVal, leftIdx});
            }
        }
    }

    // Sort by left/bottom tile index for grouping
    std::sort(hRules.begin(), hRules.end(), [](const HRule& a, const HRule& b) {
        return a.leftIdx < b.leftIdx;
    });
    std::sort(vRules.begin(), vRules.end(), [](const VRule& a, const VRule& b) {
        return a.bottomIdx < b.bottomIdx;
    });

    // Write horizontal rules
    for (auto& h : hRules) {
        auto xmlH = xmlNeighbors.appendChild("horizontal");
        xmlH.setAttribute("left", h.left);
        xmlH.setAttribute("right", h.right);
    }

    // Write vertical rules
    for (auto& v : vRules) {
        auto xmlV = xmlNeighbors.appendChild("vertical");
        xmlV.setAttribute("bottom", v.bottom);
        xmlV.setAttribute("top", v.top);
    }

    // Subsets — auto-generate "connected" subset with only tiles that have neighbors
    auto connectedTiles = getTilesWithConnections();
    if (!connectedTiles.empty()) {
        auto xmlSubsets = set.appendChild("subsets");
        auto xmlSubset = xmlSubsets.appendChild("subset");
        xmlSubset.setAttribute("name", "connected");
        for (auto& name : connectedTiles) {
            auto xmlSTile = xmlSubset.appendChild("tile");
            xmlSTile.setAttribute("name", name);
        }
    }

    xml.save(path);
    ofLogNotice("TileManager") << "Saved XML to " << path;
}
